parkingweb/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import login, register,home

urlpatterns = [
    path('',home),
    path('carposition/',include('carposition.urls')),
    path('tariff/',include('tariff.urls')),
    path('users/',include('users.urls')),
    path('login/',login,name='login'),
    path('register/',register,name='register'),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home',views.home,name='home'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('user_detail',views.user_detail,name='user_detail'),
]

parkingweb/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from users.models import UserInfo

class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', 
                               widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入用户名'}))
    password = forms.CharField(label='密码', 
                               widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'请输入密码'}))

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        user = auth.authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data

class RegForm(forms.Form):
    username = forms.CharField(label='用户名', 
                               max_length=30,
                               min_length=3,
                               widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入3-30位用户名'}))
    email = forms.EmailField(label='邮箱', 
                             widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'请输入邮箱'}))
    password = forms.CharField(label='密码', 
                               min_length=6,
                               widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'请输入密码'}))
    password_again = forms.CharField(label='再输入一次密码', 
                                     min_length=6,
                                     widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'再输入一次密码'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已存在')
        return email

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('两次输入的密码不一致')
        return password_again

class UserDetailForm(forms.Form):
    # user_name = models.CharField(u'用户名',max_length=15,default='')    
    user_phone = forms.CharField(label=u'手机号码',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入手机号码'}))
    car_number = forms.CharField(label=u'车牌号',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入车牌号'}))
    car_type = forms.CharField(label=u'车型',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入车型'}))
    car_color = forms.CharField(label=u'车色',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入车色'}))
    car_kind = forms.CharField(label=u'车种',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入车种'}))

    def clean(self):
        user_phone = self.cleaned_data['user_phone']
        car_number = self.cleaned_data['car_number']
        car_type = self.cleaned_data['car_type']
        car_color = self.cleaned_data['car_color']
        car_kind = self.cleaned_data['car_kind']
        return self.cleaned_data    
    # def clean_user_phone(self):
    #     user_phone = self.cleaned_data['user_phone']
    #     if UserInfo.objects.filter(user_phone=user_phone).exists():
    #         raise forms.ValidationError('用户名')

templates/car_posi_index.html
{% extends 'base.html' %}

{% block title %}
    停车系统|
{% endblock %}
{% load staticfiles %}
{% block content %}

<div style="width:100%;text-align: center;margin: 0 auto;position: absolute;">
    <!-- 登录界面 -->
    <div id="windows1">
        <div id="loginbox">
                {% for item in positions_list %}
                    <h4 > <a style="color:white" href="/carposition/order_position/{{ item.pk }}"> {{ item.position_num}}</a> </h4>
                {% endfor %}
            <!-- <h2 style="color:white">当前剩余车位：</h2>
            <table class="table">
                    <thead>                        
                                
                    </thead>
                    <tbody>
                        {% for item in positions_list %}
                        <td>
                            <h4 > <a style="color:white" href="/carposition/order_position/{{ item.pk }}"> {{ item.position_num}}</a> </h4>
                        </td>
                        {% endfor %}
                    </tbody>
            </table>                     -->
        </div>        
    </div>            
</div>

<div id="templatemo_banner_slide" class="container_wapper">
    <div class="camera_wrap camera_emboss" id="camera_slide">
        <!-- 背景图片 -->
        <div data-src="{% static '/login/images/banner_slide_01.jpg' %}"></div>
        <div data-src="{% static '/login/images/banner_slide_02.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_03.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_04.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_05.jpg'  %}"></div>
    </div>
    <!-- #camera_wrap_3 -->
</div>
<!-- <form action="" method="POST">
    {% csrf_token %}
    {% for field in login_form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        <p>{{ field.errors.as_text }}</p>
    {% endfor %}
    <span>{{ login_form.non_field_errors }}</span>
    <input type="submit" value="登录">
</form> -->
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
    停车系统|首页
{% endblock %}
{% load staticfiles %}
{% block content %}

<div style="width:100%;text-align: center;margin: 0 auto;position: absolute;">
    <!-- 登录界面 -->
    
    <div id="windows1">
        <div id="loginbox">
            <h1>欢迎来到停车管理系统</h1>
            <h2 class="normal_text">当前用户：{{ user.username }}</h2>
            
            <h4 class="normal_text">要使用本系统，请先登录本系统</h4>
            <a class="normal_text" href="{% url 'login' %}">登陆</a>
            <a class="normal_text" href="{% url 'register' %}">注册</a>
            <div>
                <p class="normal_text">当前剩余车位：<b> {{ car_pos_num }} </b>个</p>
                {% if user.is_authenticated %}
                    <a class="normal_text" href="/carposition/car_posi_index" type="button" >预定车位</a>        
                {% else %}
                    <a class="normal_text" type="button" disabled="disabled">预定车位[未登录]</a>
                {% endif %}
            </div>
        </div>        
    </div>
    </div>            
</div>

<div id="templatemo_banner_slide" class="container_wapper">
    <div class="camera_wrap camera_emboss" id="camera_slide">
        <!-- 背景图片 -->
        <div data-src="{% static '/login/images/banner_slide_01.jpg' %}"></div>
        <div data-src="{% static '/login/images/banner_slide_02.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_03.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_04.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_05.jpg'  %}"></div>
    </div>
    <!-- #camera_wrap_3 -->
</div>
<!-- <form action="" method="POST">
    {% csrf_token %}
    {% for field in login_form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        <p>{{ field.errors.as_text }}</p>
    {% endfor %}
    <span>{{ login_form.non_field_errors }}</span>
    <input type="submit" value="登录">
</form> -->
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
    停车系统|登录
{% endblock %}
{% load staticfiles %}
{% block content %}
<!--小键盘承载器-->
<canvas class="cavs"></canvas>
<div style="width:100%;text-align: center;margin: 0 auto;position: absolute;">
    <!-- 登录界面 -->
    <div id="windows1">
    <div id="loginbox" >	
        <form action="" method="post" name="loginForm" id="loginForm">
            {% csrf_token %}
            <div class="control-group normal_text">					
                <h3 style="text-align:center";style="font-family:verdana;color:white;font-size:40px;">
                    小区停车场智能管理系统
                </h3>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_lg">
                        <i><img height="37" src="{% static '/login/user.png' %}" /></i>
                        </span><input type="text" name="username" required id="id_username" id="loginname" value="" placeholder="请输入姓名" />
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_ly">
                        <i><img height="37" src="{% static '/login/suo.png' %}" /></i>
                        </span><input type="password" name="password" required id="id_password" id="password" placeholder="请输入密码" class="keypad" keypadMode="full" allowKeyboard="true" value=""/>
                    </div>
                </div>
            </div>
            <div style="float:right;padding-right:10%;">
                <div style="float: left;margin-top:3px;margin-right:2px;">
                    <font color="white">记住密码</font>
                </div>
                <div style="float: left;">
                    <input name="form-field-checkbox" id="saveid" type="checkbox"
                        onclick="savePaw();" style="padding-top:0px;" />
                </div>
            </div>
            <div class="form-actions">
                <div style="width:86%;padding-left:8%;">
                    <c:if test="${pd.isZhuce == 'yes' }">
                    <span class="pull-right" style="padding-right:3%;"><a href="/register" type="submit" class="btn btn-success">注册</a></span>
                    </c:if>
                    <span class="pull-right"><input onclick="severCheck();" class="flip-link btn btn-info" id="to-recover" type="submit" value="登录"></span>
                </div>
            </div>
        </form>
    </div>
    </div>
    
    
    
</div>

<div id="templatemo_banner_slide" class="container_wapper">
    <div class="camera_wrap camera_emboss" id="camera_slide">
        <!-- 背景图片 -->
        <div data-src="{% static '/login/images/banner_slide_01.jpg' %}"></div>
        <div data-src="{% static '/login/images/banner_slide_02.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_03.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_04.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_05.jpg'  %}"></div>
    </div>
    <!-- #camera_wrap_3 -->
</div>
<!-- <form action="" method="POST">
    {% csrf_token %}
    {% for field in login_form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        <p>{{ field.errors.as_text }}</p>
    {% endfor %}
    <span>{{ login_form.non_field_errors }}</span>
    <input type="submit" value="登录">
</form> -->
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    停车系统|注册
{% endblock %}
{% load staticfiles %}
{% block content %}
<!--小键盘承载器-->
<canvas class="cavs"></canvas>
<div style="width:100%;text-align: center;margin: 0 auto;position: absolute;">
    <!-- 登录界面 -->
    <div id="windows1">
    <div id="loginbox" >	
        <form action="" method="post" name="loginForm" id="loginForm">
            {% csrf_token %}
            <div class="control-group normal_text">					
                <h3 style="text-align:center";style="font-family:verdana;color:white;font-size:40px;">
                    小区停车场智能管理系统
                </h3>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_lg">
                        <i><img height="37" src="{% static '/login/user.png' %}" /></i>
                        </span><input type="text" name="username" required id="id_username" id="loginname" value="" placeholder="请输入姓名" />
                    </div>
                </div>
            </div>
            <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_lg">
                            <i><img height="37" src="{% static '/login/user.png' %}" /></i>
                            </span><input type="email" name="email"  required required id="id_username" id="id_email" value="" placeholder="请输入邮箱" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                        <div class="controls">
                            <div class="main_input_box">
                                <span class="add-on bg_ly">
                                <i><img height="37" src="{% static '/login/suo.png' %}" /></i>
                                </span><input type="text" name="idcar" required id="idcar" id="loginname" placeholder="请输入身份证" class="keypad" keypadMode="full" allowKeyboard="true" value=""/>
                            </div>
                        </div>
                    </div>
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_ly">
                        <i><img height="37" src="{% static '/login/suo.png' %}" /></i>
                        </span><input type="password" name="password" required id="id_password" id="password" placeholder="请输入密码" class="keypad" keypadMode="full" allowKeyboard="true" value=""/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_ly">
                            <i><img height="37" src="{% static '/login/suo.png' %}" /></i>
                            </span><input type="password" name="password_again" id="id_password_again" required placeholder="再输入一次密码" class="keypad" keypadMode="full" allowKeyboard="true" value=""/>
                        </div>
                    </div>
                </div>
            
            <div style="float:right;padding-right:10%;">
                <div style="float: left;margin-top:3px;margin-right:2px;">
                    <font color="white">记住密码</font>
                </div>
                <div style="float: left;">
                    <input name="form-field-checkbox" id="saveid" type="checkbox"
                        onclick="savePaw();" style="padding-top:0px;" />
                </div>
            </div>
            <div class="form-actions">
                <div style="width:86%;padding-left:8%;">                    
                    </c:if>
                    <span class="pull-right"><input onclick="severCheck();" class="flip-link btn btn-info" id="to-recover" type="submit" value="注册"></span>
                </div>
            </div>
        </form>
    </div>
    </div>
    
    
    
</div>

<div id="templatemo_banner_slide" class="container_wapper">
    <div class="camera_wrap camera_emboss" id="camera_slide">
        <!-- 背景图片 -->
        <div data-src="{% static '/login/images/banner_slide_01.jpg' %}"></div>
        <div data-src="{% static '/login/images/banner_slide_02.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_03.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_04.jpg'  %}"></div>
        <div data-src="{% static '/login/images/banner_slide_05.jpg'  %}"></div>
    </div>
    <!-- #camera_wrap_3 -->
</div>
<!-- <form action="" method="POST">
    {% csrf_token %}
    {% for field in login_form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        <p>{{ field.errors.as_text }}</p>
    {% endfor %}
    <span>{{ login_form.non_field_errors }}</span>
    <input type="submit" value="登录">
</form> -->
{% endblock %}

templates/user_detail.html
{% extends 'base.html' %}

{% block title %}
    停车系统|首页
{% endblock %}

{% block content %}
<h3>当前用户：{{ user.username}}</h3>
<form action="" method="POST">
    {% csrf_token %}
    {% for field in user_form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        <p >{{ field.errors.as_text }}</p>
    {% endfor %}
    <span>{{ user_form.non_field_errors }}</span>
    <input type="submit" value="注册">
</form>
{% endblock %}